---
- hosts: all
  sudo: yes

  vars:
    dbroot: "{{ lookup('password', '/tmp/' + '.mysqlpass length=15') }}"
    pma: "{{ lookup('password', '/tmp/' + '.pmapass length=15') }}"

  tasks:
    - debug: msg="{{ dbroot }} is a dbroot"

    - debug: msg="{{ pma }} is a pma"

    - name: Add MariaDB apt key
      apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xCBCB082A1BB943DB state=present

    - name: Add MariaDB apt repository
      apt_repository: repo='deb http://mirrors.syringanetworks.net/mariadb/repo/10.0/ubuntu trusty main'
    ##
    # Apt package installation of required software.
    #
    - name: General | Install required packages.
      action: apt pkg={{ item }} state=installed
      tags: common
      with_items:
        - php5-fpm
        - php5-mcrypt
        - nginx
        - mariadb-server
        - software-properties-common
        - php5-mysql
        - php5-gd
        - php5-curl
        - php5-json
        - python-mysqldb
        - phpmyadmin

    - name: Ensure MySQL is running
      service: name=mysql state=started enabled=true

    - name: Update MySQL Root Password
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ dbroot }}"
        login_user: root
        login_password: "{{ dbroot }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
          - 127.0.0.1
          - ::1
          - localhost
    - name: Copy the my.cnf
      template: src=templates/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

    - name: Removing default NGINX configuration
      shell: rm /etc/nginx/sites-available/default

    - name: Removing default NGINX configuration
      shell: rm /etc/nginx/sites-enabled/default

    - name: Creating custom default NGINX configuration
      template: src=templates/default.j2 dest=/etc/nginx/sites-available/default owner=www-data mode=0644

    - name: Linking default NGINX configuration to sites-enabled
      shell: ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
      ignore_errors: yes

    - name: Linking phpMyAdmin to the default NGINX document root
      shell: ln -s /usr/share/phpmyadmin /usr/share/nginx/html
      ignore_errors: yes

    - name: Generate .htpasswd for PHPMyAdmin
      shell: sudo printf "serverinfo:$(openssl passwd -crypt {{ pma }})\n" >> /etc/nginx/.htpasswd

    - name: Copy the .phpmyadminpass
      template: src=templates/phpmyadminpass.j2 dest=/root/.phpmyadminpass owner=root mode=0600

    - name: Restarting NGINX and php5-fpm
      service: name=nginx state=restarted
      service: name=php5-fpm state=restarted
