VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :delta do |x|
    x.vm.box = "hashicorp/precise64"
    x.vm.hostname = "ubuntu1404ebs"

    x.vm.provider :virtualbox do |v|
      v.name = "ubuntu1404ebs"
    end
    x.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV['AWS_KEY']
      aws.secret_access_key = ENV['AWS_SECRET']
      aws.keypair_name = ENV['AWS_KEYNAME']
      aws.ami = "ami-c51338f5"
      aws.region = "us-west-2"
      aws.instance_type = "t2.small"
      aws.security_groups = [ 'ssh' ]
      override.vm.box = "dummy"
      override.ssh.username = "ubuntu"
      aws.block_device_mapping = [{
        'DeviceName' => '/dev/sda1',
        'Ebs.VolumeSize' => 8,
        'Ebs.VolumeType' => 'gp2',
        'Ebs.DeleteOnTermination' => 'true' }]
      override.ssh.private_key_path = ENV['AWS_KEYPATH']
          end
        end
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
      end
end
